git-alias: cleanups

diff --git a/bin/git-alias b/bin/git-alias
--- a/bin/git-alias
+++ b/bin/git-alias
@@ -1,10 +1,15 @@
 #!/bin/sh
+# shellcheck disable=SC2039
+#
 #
 # Manage git aliases.
 #
 
+SCRIPT=$(basename "$0")
+
+
 usage() {
-    echo "Usage: $(basename $0)" "$@"
+    echo "Usage: $SCRIPT" "$@" >&2
     exit 1
 }
 
@@ -34,7 +39,7 @@ remove_alias() {
 
 
 list_aliases() {
-    git config --global -l | sed -n 's/^alias\.\([^=]\+\) *= *\(.*\)/\1 = \2/p' | sort
+    git config --global -l | sed -n 's/^alias\.\([^=]\+\) *= *\(.*\)/\1: \2/p' | sort
 }
 
 
@@ -48,7 +53,11 @@ case "$cmd" in
     remove)
         remove_alias "$@"
         ;;
+    list | "")
+        list_aliases "$@"
+        ;;
     *)
-        list_aliases
+        echo "invalid command: $cmd" >&2
+        exit 2
         ;;
 esac
